os:
  - linux
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - language: generic
      os: osx
      python:
        - "3"
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
# command to install dependencies
install:
    - "pip install -r tests/requirements.txt"
    - "python setup.py install"
# command to run tests
script: python -m unittest discover
